version: '2'
services:
  message-server:
    container_name: web-app-template
    build:
      context: web-app-template
      dockerfile: Dockerfile
    image: web-app-template:latest
    ports:
      - 18081:8081
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge